// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace atwork_pb_msgs {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class AttentionMessage {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_atwork_pb_msgs_AttentionMessage__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.AttentionMessage, global::atwork_pb_msgs.AttentionMessage.Builder> internal__static_atwork_pb_msgs_AttentionMessage__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static AttentionMessage() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "ChZBdHRlbnRpb25NZXNzYWdlLnByb3RvEg5hdHdvcmtfcGJfbXNncyJvChBB", 
              "dHRlbnRpb25NZXNzYWdlEg8KB21lc3NhZ2UYASACKAkSFAoMdGltZV90b19z", 
              "aG93GAIgASgCEgwKBHRlYW0YAyABKAkiJgoIQ29tcFR5cGUSDAoHQ09NUF9J", 
              "RBDQDxIMCghNU0dfVFlQRRACQjAKFm9yZy5hdHdvcmsuY29tbW9uX21zZ3NC", 
            "FkF0dGVudGlvbk1lc3NhZ2VQcm90b3M="));
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_atwork_pb_msgs_AttentionMessage__Descriptor = Descriptor.MessageTypes[0];
          internal__static_atwork_pb_msgs_AttentionMessage__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.AttentionMessage, global::atwork_pb_msgs.AttentionMessage.Builder>(internal__static_atwork_pb_msgs_AttentionMessage__Descriptor,
                  new string[] { "Message", "TimeToShow", "Team", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class AttentionMessage : pb::GeneratedMessage<AttentionMessage, AttentionMessage.Builder> {
    private AttentionMessage() { }
    private static readonly AttentionMessage defaultInstance = new AttentionMessage().MakeReadOnly();
    private static readonly string[] _attentionMessageFieldNames = new string[] { "message", "team", "time_to_show" };
    private static readonly uint[] _attentionMessageFieldTags = new uint[] { 10, 26, 21 };
    public static AttentionMessage DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override AttentionMessage DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override AttentionMessage ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::atwork_pb_msgs.Proto.AttentionMessage.internal__static_atwork_pb_msgs_AttentionMessage__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<AttentionMessage, AttentionMessage.Builder> InternalFieldAccessors {
      get { return global::atwork_pb_msgs.Proto.AttentionMessage.internal__static_atwork_pb_msgs_AttentionMessage__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum CompType {
        COMP_ID = 2000,
        MSG_TYPE = 2,
      }
      
    }
    #endregion
    
    public const int MessageFieldNumber = 1;
    private bool hasMessage;
    private string message_ = "";
    public bool HasMessage {
      get { return hasMessage; }
    }
    public string Message {
      get { return message_; }
    }
    
    public const int TimeToShowFieldNumber = 2;
    private bool hasTimeToShow;
    private float timeToShow_;
    public bool HasTimeToShow {
      get { return hasTimeToShow; }
    }
    public float TimeToShow {
      get { return timeToShow_; }
    }
    
    public const int TeamFieldNumber = 3;
    private bool hasTeam;
    private string team_ = "";
    public bool HasTeam {
      get { return hasTeam; }
    }
    public string Team {
      get { return team_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasMessage) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _attentionMessageFieldNames;
      if (hasMessage) {
        output.WriteString(1, field_names[0], Message);
      }
      if (hasTimeToShow) {
        output.WriteFloat(2, field_names[2], TimeToShow);
      }
      if (hasTeam) {
        output.WriteString(3, field_names[1], Team);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasMessage) {
        size += pb::CodedOutputStream.ComputeStringSize(1, Message);
      }
      if (hasTimeToShow) {
        size += pb::CodedOutputStream.ComputeFloatSize(2, TimeToShow);
      }
      if (hasTeam) {
        size += pb::CodedOutputStream.ComputeStringSize(3, Team);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static AttentionMessage ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static AttentionMessage ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static AttentionMessage ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static AttentionMessage ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static AttentionMessage ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static AttentionMessage ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static AttentionMessage ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static AttentionMessage ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static AttentionMessage ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static AttentionMessage ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private AttentionMessage MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(AttentionMessage prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<AttentionMessage, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(AttentionMessage cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private AttentionMessage result;
      
      private AttentionMessage PrepareBuilder() {
        if (resultIsReadOnly) {
          AttentionMessage original = result;
          result = new AttentionMessage();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override AttentionMessage MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::atwork_pb_msgs.AttentionMessage.Descriptor; }
      }
      
      public override AttentionMessage DefaultInstanceForType {
        get { return global::atwork_pb_msgs.AttentionMessage.DefaultInstance; }
      }
      
      public override AttentionMessage BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is AttentionMessage) {
          return MergeFrom((AttentionMessage) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(AttentionMessage other) {
        if (other == global::atwork_pb_msgs.AttentionMessage.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasMessage) {
          Message = other.Message;
        }
        if (other.HasTimeToShow) {
          TimeToShow = other.TimeToShow;
        }
        if (other.HasTeam) {
          Team = other.Team;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_attentionMessageFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _attentionMessageFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasMessage = input.ReadString(ref result.message_);
              break;
            }
            case 21: {
              result.hasTimeToShow = input.ReadFloat(ref result.timeToShow_);
              break;
            }
            case 26: {
              result.hasTeam = input.ReadString(ref result.team_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasMessage {
        get { return result.hasMessage; }
      }
      public string Message {
        get { return result.Message; }
        set { SetMessage(value); }
      }
      public Builder SetMessage(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder ClearMessage() {
        PrepareBuilder();
        result.hasMessage = false;
        result.message_ = "";
        return this;
      }
      
      public bool HasTimeToShow {
        get { return result.hasTimeToShow; }
      }
      public float TimeToShow {
        get { return result.TimeToShow; }
        set { SetTimeToShow(value); }
      }
      public Builder SetTimeToShow(float value) {
        PrepareBuilder();
        result.hasTimeToShow = true;
        result.timeToShow_ = value;
        return this;
      }
      public Builder ClearTimeToShow() {
        PrepareBuilder();
        result.hasTimeToShow = false;
        result.timeToShow_ = 0F;
        return this;
      }
      
      public bool HasTeam {
        get { return result.hasTeam; }
      }
      public string Team {
        get { return result.Team; }
        set { SetTeam(value); }
      }
      public Builder SetTeam(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTeam = true;
        result.team_ = value;
        return this;
      }
      public Builder ClearTeam() {
        PrepareBuilder();
        result.hasTeam = false;
        result.team_ = "";
        return this;
      }
    }
    static AttentionMessage() {
      object.ReferenceEquals(global::atwork_pb_msgs.Proto.AttentionMessage.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
