// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace atwork_pb_msgs {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class RobotStatusReport {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_atwork_pb_msgs_RobotStatus__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.RobotStatus, global::atwork_pb_msgs.RobotStatus.Builder> internal__static_atwork_pb_msgs_RobotStatus__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_atwork_pb_msgs_RobotStatusReport__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.RobotStatusReport, global::atwork_pb_msgs.RobotStatusReport.Builder> internal__static_atwork_pb_msgs_RobotStatusReport__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static RobotStatusReport() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "ChdSb2JvdFN0YXR1c1JlcG9ydC5wcm90bxIOYXR3b3JrX3BiX21zZ3Mi8wEK", 
              "C1JvYm90U3RhdHVzEjoKCmNhcGFiaWxpdHkYASABKA4yJi5hdHdvcmtfcGJf", 
              "bXNncy5Sb2JvdFN0YXR1cy5DYXBhYmlsaXR5EhUKDWZ1bmN0aW9uYWxpdHkY", 
              "AiABKAkSEQoJbWV0YV9kYXRhGAMgASgJIicKCENvbXBUeXBlEgwKB0NPTVBf", 
              "SUQQ0A8SDQoITVNHX1RZUEUQ2QQiVQoKQ2FwYWJpbGl0eRILCgdVTktOT1dO", 
              "EAASDgoKTkFWSUdBVElPThABEhAKDE1BTklQVUxBVElPThACEg4KClBFUkNF", 
              "UFRJT04QAxIICgRUQVNLEAQiaQoRUm9ib3RTdGF0dXNSZXBvcnQSKwoGc3Rh", 
              "dHVzGAEgAygLMhsuYXR3b3JrX3BiX21zZ3MuUm9ib3RTdGF0dXMiJwoIQ29t", 
              "cFR5cGUSDAoHQ09NUF9JRBDQDxINCghNU0dfVFlQRRDaBEIxChZvcmcuYXR3", 
            "b3JrLmNvbW1vbl9tc2dzQhdSb2JvdFN0YXR1c1JlcG9ydFByb3Rvcw=="));
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_atwork_pb_msgs_RobotStatus__Descriptor = Descriptor.MessageTypes[0];
          internal__static_atwork_pb_msgs_RobotStatus__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.RobotStatus, global::atwork_pb_msgs.RobotStatus.Builder>(internal__static_atwork_pb_msgs_RobotStatus__Descriptor,
                  new string[] { "Capability", "Functionality", "MetaData", });
          internal__static_atwork_pb_msgs_RobotStatusReport__Descriptor = Descriptor.MessageTypes[1];
          internal__static_atwork_pb_msgs_RobotStatusReport__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.RobotStatusReport, global::atwork_pb_msgs.RobotStatusReport.Builder>(internal__static_atwork_pb_msgs_RobotStatusReport__Descriptor,
                  new string[] { "Status", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class RobotStatus : pb::GeneratedMessage<RobotStatus, RobotStatus.Builder> {
    private RobotStatus() { }
    private static readonly RobotStatus defaultInstance = new RobotStatus().MakeReadOnly();
    private static readonly string[] _robotStatusFieldNames = new string[] { "capability", "functionality", "meta_data" };
    private static readonly uint[] _robotStatusFieldTags = new uint[] { 8, 18, 26 };
    public static RobotStatus DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override RobotStatus DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override RobotStatus ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::atwork_pb_msgs.Proto.RobotStatusReport.internal__static_atwork_pb_msgs_RobotStatus__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<RobotStatus, RobotStatus.Builder> InternalFieldAccessors {
      get { return global::atwork_pb_msgs.Proto.RobotStatusReport.internal__static_atwork_pb_msgs_RobotStatus__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum CompType {
        COMP_ID = 2000,
        MSG_TYPE = 601,
      }
      
      public enum Capability {
        UNKNOWN = 0,
        NAVIGATION = 1,
        MANIPULATION = 2,
        PERCEPTION = 3,
        TASK = 4,
      }
      
    }
    #endregion
    
    public const int CapabilityFieldNumber = 1;
    private bool hasCapability;
    private global::atwork_pb_msgs.RobotStatus.Types.Capability capability_ = global::atwork_pb_msgs.RobotStatus.Types.Capability.UNKNOWN;
    public bool HasCapability {
      get { return hasCapability; }
    }
    public global::atwork_pb_msgs.RobotStatus.Types.Capability Capability {
      get { return capability_; }
    }
    
    public const int FunctionalityFieldNumber = 2;
    private bool hasFunctionality;
    private string functionality_ = "";
    public bool HasFunctionality {
      get { return hasFunctionality; }
    }
    public string Functionality {
      get { return functionality_; }
    }
    
    public const int MetaDataFieldNumber = 3;
    private bool hasMetaData;
    private string metaData_ = "";
    public bool HasMetaData {
      get { return hasMetaData; }
    }
    public string MetaData {
      get { return metaData_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _robotStatusFieldNames;
      if (hasCapability) {
        output.WriteEnum(1, field_names[0], (int) Capability, Capability);
      }
      if (hasFunctionality) {
        output.WriteString(2, field_names[1], Functionality);
      }
      if (hasMetaData) {
        output.WriteString(3, field_names[2], MetaData);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasCapability) {
        size += pb::CodedOutputStream.ComputeEnumSize(1, (int) Capability);
      }
      if (hasFunctionality) {
        size += pb::CodedOutputStream.ComputeStringSize(2, Functionality);
      }
      if (hasMetaData) {
        size += pb::CodedOutputStream.ComputeStringSize(3, MetaData);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static RobotStatus ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RobotStatus ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RobotStatus ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RobotStatus ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RobotStatus ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RobotStatus ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static RobotStatus ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static RobotStatus ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static RobotStatus ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RobotStatus ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private RobotStatus MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(RobotStatus prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<RobotStatus, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(RobotStatus cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private RobotStatus result;
      
      private RobotStatus PrepareBuilder() {
        if (resultIsReadOnly) {
          RobotStatus original = result;
          result = new RobotStatus();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override RobotStatus MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::atwork_pb_msgs.RobotStatus.Descriptor; }
      }
      
      public override RobotStatus DefaultInstanceForType {
        get { return global::atwork_pb_msgs.RobotStatus.DefaultInstance; }
      }
      
      public override RobotStatus BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is RobotStatus) {
          return MergeFrom((RobotStatus) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(RobotStatus other) {
        if (other == global::atwork_pb_msgs.RobotStatus.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasCapability) {
          Capability = other.Capability;
        }
        if (other.HasFunctionality) {
          Functionality = other.Functionality;
        }
        if (other.HasMetaData) {
          MetaData = other.MetaData;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_robotStatusFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _robotStatusFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.capability_, out unknown)) {
                result.hasCapability = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 18: {
              result.hasFunctionality = input.ReadString(ref result.functionality_);
              break;
            }
            case 26: {
              result.hasMetaData = input.ReadString(ref result.metaData_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasCapability {
       get { return result.hasCapability; }
      }
      public global::atwork_pb_msgs.RobotStatus.Types.Capability Capability {
        get { return result.Capability; }
        set { SetCapability(value); }
      }
      public Builder SetCapability(global::atwork_pb_msgs.RobotStatus.Types.Capability value) {
        PrepareBuilder();
        result.hasCapability = true;
        result.capability_ = value;
        return this;
      }
      public Builder ClearCapability() {
        PrepareBuilder();
        result.hasCapability = false;
        result.capability_ = global::atwork_pb_msgs.RobotStatus.Types.Capability.UNKNOWN;
        return this;
      }
      
      public bool HasFunctionality {
        get { return result.hasFunctionality; }
      }
      public string Functionality {
        get { return result.Functionality; }
        set { SetFunctionality(value); }
      }
      public Builder SetFunctionality(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFunctionality = true;
        result.functionality_ = value;
        return this;
      }
      public Builder ClearFunctionality() {
        PrepareBuilder();
        result.hasFunctionality = false;
        result.functionality_ = "";
        return this;
      }
      
      public bool HasMetaData {
        get { return result.hasMetaData; }
      }
      public string MetaData {
        get { return result.MetaData; }
        set { SetMetaData(value); }
      }
      public Builder SetMetaData(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasMetaData = true;
        result.metaData_ = value;
        return this;
      }
      public Builder ClearMetaData() {
        PrepareBuilder();
        result.hasMetaData = false;
        result.metaData_ = "";
        return this;
      }
    }
    static RobotStatus() {
      object.ReferenceEquals(global::atwork_pb_msgs.Proto.RobotStatusReport.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class RobotStatusReport : pb::GeneratedMessage<RobotStatusReport, RobotStatusReport.Builder> {
    private RobotStatusReport() { }
    private static readonly RobotStatusReport defaultInstance = new RobotStatusReport().MakeReadOnly();
    private static readonly string[] _robotStatusReportFieldNames = new string[] { "status" };
    private static readonly uint[] _robotStatusReportFieldTags = new uint[] { 10 };
    public static RobotStatusReport DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override RobotStatusReport DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override RobotStatusReport ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::atwork_pb_msgs.Proto.RobotStatusReport.internal__static_atwork_pb_msgs_RobotStatusReport__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<RobotStatusReport, RobotStatusReport.Builder> InternalFieldAccessors {
      get { return global::atwork_pb_msgs.Proto.RobotStatusReport.internal__static_atwork_pb_msgs_RobotStatusReport__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum CompType {
        COMP_ID = 2000,
        MSG_TYPE = 602,
      }
      
    }
    #endregion
    
    public const int StatusFieldNumber = 1;
    private pbc::PopsicleList<global::atwork_pb_msgs.RobotStatus> status_ = new pbc::PopsicleList<global::atwork_pb_msgs.RobotStatus>();
    public scg::IList<global::atwork_pb_msgs.RobotStatus> StatusList {
      get { return status_; }
    }
    public int StatusCount {
      get { return status_.Count; }
    }
    public global::atwork_pb_msgs.RobotStatus GetStatus(int index) {
      return status_[index];
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _robotStatusReportFieldNames;
      if (status_.Count > 0) {
        output.WriteMessageArray(1, field_names[0], status_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      foreach (global::atwork_pb_msgs.RobotStatus element in StatusList) {
        size += pb::CodedOutputStream.ComputeMessageSize(1, element);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static RobotStatusReport ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static RobotStatusReport ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static RobotStatusReport ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static RobotStatusReport ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private RobotStatusReport MakeReadOnly() {
      status_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(RobotStatusReport prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<RobotStatusReport, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(RobotStatusReport cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private RobotStatusReport result;
      
      private RobotStatusReport PrepareBuilder() {
        if (resultIsReadOnly) {
          RobotStatusReport original = result;
          result = new RobotStatusReport();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override RobotStatusReport MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::atwork_pb_msgs.RobotStatusReport.Descriptor; }
      }
      
      public override RobotStatusReport DefaultInstanceForType {
        get { return global::atwork_pb_msgs.RobotStatusReport.DefaultInstance; }
      }
      
      public override RobotStatusReport BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is RobotStatusReport) {
          return MergeFrom((RobotStatusReport) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(RobotStatusReport other) {
        if (other == global::atwork_pb_msgs.RobotStatusReport.DefaultInstance) return this;
        PrepareBuilder();
        if (other.status_.Count != 0) {
          result.status_.Add(other.status_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_robotStatusReportFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _robotStatusReportFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadMessageArray(tag, field_name, result.status_, global::atwork_pb_msgs.RobotStatus.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<global::atwork_pb_msgs.RobotStatus> StatusList {
        get { return PrepareBuilder().status_; }
      }
      public int StatusCount {
        get { return result.StatusCount; }
      }
      public global::atwork_pb_msgs.RobotStatus GetStatus(int index) {
        return result.GetStatus(index);
      }
      public Builder SetStatus(int index, global::atwork_pb_msgs.RobotStatus value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.status_[index] = value;
        return this;
      }
      public Builder SetStatus(int index, global::atwork_pb_msgs.RobotStatus.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.status_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddStatus(global::atwork_pb_msgs.RobotStatus value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.status_.Add(value);
        return this;
      }
      public Builder AddStatus(global::atwork_pb_msgs.RobotStatus.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.status_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeStatus(scg::IEnumerable<global::atwork_pb_msgs.RobotStatus> values) {
        PrepareBuilder();
        result.status_.Add(values);
        return this;
      }
      public Builder ClearStatus() {
        PrepareBuilder();
        result.status_.Clear();
        return this;
      }
    }
    static RobotStatusReport() {
      object.ReferenceEquals(global::atwork_pb_msgs.Proto.RobotStatusReport.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
