// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021,2237
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace atwork_pb_msgs {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Time {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_atwork_pb_msgs_Time__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.Time, global::atwork_pb_msgs.Time.Builder> internal__static_atwork_pb_msgs_Time__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static Time() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "CgpUaW1lLnByb3RvEg5hdHdvcmtfcGJfbXNncyIhCgRUaW1lEgsKA3NlYxgB", 
              "IAIoAxIMCgRuc2VjGAIgAigDQiQKFm9yZy5hdHdvcmsuY29tbW9uX21zZ3NC", 
            "ClRpbWVQcm90b3M="));
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_atwork_pb_msgs_Time__Descriptor = Descriptor.MessageTypes[0];
          internal__static_atwork_pb_msgs_Time__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::atwork_pb_msgs.Time, global::atwork_pb_msgs.Time.Builder>(internal__static_atwork_pb_msgs_Time__Descriptor,
                  new string[] { "Sec", "Nsec", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Time : pb::GeneratedMessage<Time, Time.Builder> {
    private Time() { }
    private static readonly Time defaultInstance = new Time().MakeReadOnly();
    private static readonly string[] _timeFieldNames = new string[] { "nsec", "sec" };
    private static readonly uint[] _timeFieldTags = new uint[] { 16, 8 };
    public static Time DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override Time DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override Time ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::atwork_pb_msgs.Proto.Time.internal__static_atwork_pb_msgs_Time__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<Time, Time.Builder> InternalFieldAccessors {
      get { return global::atwork_pb_msgs.Proto.Time.internal__static_atwork_pb_msgs_Time__FieldAccessorTable; }
    }
    
    public const int SecFieldNumber = 1;
    private bool hasSec;
    private long sec_;
    public bool HasSec {
      get { return hasSec; }
    }
    public long Sec {
      get { return sec_; }
    }
    
    public const int NsecFieldNumber = 2;
    private bool hasNsec;
    private long nsec_;
    public bool HasNsec {
      get { return hasNsec; }
    }
    public long Nsec {
      get { return nsec_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasSec) return false;
        if (!hasNsec) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _timeFieldNames;
      if (hasSec) {
        output.WriteInt64(1, field_names[1], Sec);
      }
      if (hasNsec) {
        output.WriteInt64(2, field_names[0], Nsec);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasSec) {
        size += pb::CodedOutputStream.ComputeInt64Size(1, Sec);
      }
      if (hasNsec) {
        size += pb::CodedOutputStream.ComputeInt64Size(2, Nsec);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static Time ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Time ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Time ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Time ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Time ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Time ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Time ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static Time ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static Time ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Time ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private Time MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(Time prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<Time, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(Time cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private Time result;
      
      private Time PrepareBuilder() {
        if (resultIsReadOnly) {
          Time original = result;
          result = new Time();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override Time MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::atwork_pb_msgs.Time.Descriptor; }
      }
      
      public override Time DefaultInstanceForType {
        get { return global::atwork_pb_msgs.Time.DefaultInstance; }
      }
      
      public override Time BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is Time) {
          return MergeFrom((Time) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(Time other) {
        if (other == global::atwork_pb_msgs.Time.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasSec) {
          Sec = other.Sec;
        }
        if (other.HasNsec) {
          Nsec = other.Nsec;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_timeFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _timeFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasSec = input.ReadInt64(ref result.sec_);
              break;
            }
            case 16: {
              result.hasNsec = input.ReadInt64(ref result.nsec_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasSec {
        get { return result.hasSec; }
      }
      public long Sec {
        get { return result.Sec; }
        set { SetSec(value); }
      }
      public Builder SetSec(long value) {
        PrepareBuilder();
        result.hasSec = true;
        result.sec_ = value;
        return this;
      }
      public Builder ClearSec() {
        PrepareBuilder();
        result.hasSec = false;
        result.sec_ = 0L;
        return this;
      }
      
      public bool HasNsec {
        get { return result.hasNsec; }
      }
      public long Nsec {
        get { return result.Nsec; }
        set { SetNsec(value); }
      }
      public Builder SetNsec(long value) {
        PrepareBuilder();
        result.hasNsec = true;
        result.nsec_ = value;
        return this;
      }
      public Builder ClearNsec() {
        PrepareBuilder();
        result.hasNsec = false;
        result.nsec_ = 0L;
        return this;
      }
    }
    static Time() {
      object.ReferenceEquals(global::atwork_pb_msgs.Proto.Time.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
